### ISSUE TITLE
Bilder werden nicht angezeigt, obwohl imagetag vorhanden ist.

### ISSUE THREAD

**Issue by gmbo** [penpendede/stolperstein-bonn#6]
Wenn der imagetag die volle Adresse enthält werden die Biler nicht gezeigt obwohl das Icon blau zegt.

Beispiel: image=https://commons.wikimedia.org/wiki/File:Stolperstein_Krackser_Str_203_Bielefeld.JPG

So sind viele Steine getaggt, da dies die Kopie der Adresszeile von commons ist.

**Comment by penpendede** [comment]
Mir ist bewusst, dass die Verarbeitung der **image**-Angabe noch verbesserungswürdig ist. Aktuell baue ich einiges um aber ich werde mal schauen, dass ich das berichtete Problem in den nächsten Tagen behebe.

**Comment by penpendede** [comment]
Problem sollte nun behoben sein. Bilder von anderen Sites produzieren weiterhin Probleme - da weiß ich mir aber kaum einen Rat :frowning_face:
